version: '3.7'
services:
  docker-maintenance:
    command: --clean ${PWD}
    image: cav94mat/docker-maintenance
    environment:
      SCHEDULE: '0 4 * * *'      
    volumes:
      - '${PWD}:/${PWD}:z'
      - '/var/run/docker.sock:/var/run/docker.sock:z'