#!/bin/bash
inc() { # <<files>>
    while [ "$#" -gt 0 ]; do
        cat "$1"
        echo; shift;
    done
}
cd "$(dirname "$0")"
{
    build="$USER@$(date +%Y-%m-%d/%H:%m:%S)"
    echo '#!/bin/bash'
    echo "# Do NOT edit this file directly. Plase rebuild with \`make\`."
    echo "readonly build='$build'"
    echo ''
    inc "./src/libs/"*.lib.sh
    echo ''
    inc "./src/funcs/"*.sh
    echo ''
    inc './src/core.sh'
} > ./docker-maintenance.sh
chmod +x ./docker-maintenance.sh