#!/bin/bash
inc() { # <<files>>
    while [ "$#" -gt 0 ]; do
        cat "$1"
        echo; shift;
    done
}

cd "$(dirname "$0")"
source 'src/libs/logging.lib.sh'

output="${OUTPUT:-${OUTPUT_DIR:-.}/docker-maintenance.sh}"
build="${BUILD:-${USER}@$(date +%Y-%m-%d/%H:%m:%S)}"
install_dir="${INSTALL_DIR:-/opt/docker-maintenance}"
install_bin="${INSTALL_BIN:-/usr/bin/docker-maintenance}"

while [ "$#" -gt 0 ]; do
    op="$1"
    case "$op" in
        "compile"|"")
            log -I "Building '${build}' -> ${output}"
            {    
                echo '#!/bin/bash'
                echo "# Do NOT edit this file directly. Plase rebuild with \`make\`."
                echo "readonly build='$build'"
                echo ''
                inc "./src/libs/"*.lib.sh
                echo ''
                inc "./src/program.sh"
            } > "$output"
            chmod +x "$output"
            ;;
        "install")            
            log -I "Installing ${output} to ${install_dir}/"
            mkdir -p "${install_dir}"
            cp "${output}" "${install_dir}"/docker-maintenance.sh
            cp -RT ./scripts "${install_dir}/scripts"
            
            log -I "Symlinking ${install_bin} -> ${install_dir}/docker-maintenance.sh"
            ln -fs "/${install_dir}/docker-maintenance.sh" "${install_bin}"
            ;;
        "clean")
            rm -Rf "${install_dir}" "${install_bin}" "${output}"
            ;;
        *)
            log -E "Unsupported operation \`$op\`"
            exit 1        
    esac
    shift
done